# server配置
server:
  port: 8888
  servlet:
    context-path: /

# 连接池配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql:///digit_twin
      username: root  #开发环境
      #username: raymond
      password: 123456wmr
      driver-class-name: com.mysql.cj.jdbc.Driver
    # 配置redis
    data:
      redis:
        # 地址
        host: localhost
        # 数据库索引
        database: 0
        # 连接超时时间
        timeout: 10s
        lettuce:
          pool:
            # 连接池中的最小空闲连接
            min-idle: 0
            # 连接池中的最大空闲连接
            max-idle: 8
            # 连接池的最大数据库连接数
            max-active: 8
            # #连接池最大阻塞等待时间（使用负值表示没有限制）
            max-wait: -1ms
# mybatis-plus的配置
mybatis-plus:
  type-aliases-package: edu.whut.pojo
  global-config:
    db-config:
      logic-delete-field: isDeleted  #全局逻辑删除
      id-type: auto #主键策略自增长
      table-prefix: t_ # 设置表的前缀
#pagehelper分页插件配置
#pagehelper:
#  helperDialect: mysql
 # reasonable: true
  #supportMethodsArguments: true
  #params: count=countSql
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mqtt:
  broker: tcp://116.62.209.241:1883
  username: admin
  password: 123
  timeout: 60
  keepAlive: 20
  qos: 0
  pubTopic: data/#
  subTopic: control/1

jwt:
  token:
    tokenExpiration: 120 #有效时间,单位分钟
    tokenSignKey: server_map  #当前程序签名秘钥